apiVersion: v1
kind: ReplicationController
metadata:
  name: simpleapp-controller
spec:
  replicas: 1
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    app: webz
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        app: webz
    spec:
      containers:
      - name: simpleappz
        image: moffatja/simpleappz
        env: 
        - name: ZEUS_TOKEN
          value: "8dcccc00"
        - name: USER
          value: "jmoffat"
        ports:
        - containerPort: 9090
