apiVersion: v1
kind: Pod
metadata:
  name: vt-podz
  labels:
    app: webz
spec:
  containers:
    - name: simpleappz
      image: moffatja/simpleappz
      env:
        - name: ZEUS_TOKEN
          value: "8dcccc00"
        - name: USER
          value: "jmoffat"
      ports:
        - containerPort: 9090
